### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by tipouic** [soligen2010/RC_RX_CABELL_V3_FHSS#1]
Can you push one old version in order to see the evolution ?
Thank you

**Comment by soligen2010** [comment]
Thanks for the interest.  Unfortunately this project has slowed.  Due to a back injury I have had trouble sitting at my desk for any length of time.

The good new is that yesterday I flew 3 models using this protocol, (but not using Multiprotocol as the TX). and today I updated my board layout.

My plan is to:

Update my Multiprotocol code fork and test it.
Write some documentation.
Upload everything.

Hopefully all this week.

After that, I want to work on antenna design then do range/reliability testing.

**Comment by soligen2010** [comment]
The first release of the code has been uploaded.  Enjoy :)
