### ISSUE TITLE
Can you please advise me PWM MOTOR DRIVER

### ISSUE THREAD

**Issue by stanekTM** [soligen2010/RC_RX_CABELL_V3_FHSS#7]
Hi Soligen,
Can you please advise me.
I need to change channels AUX_1-AUX_4.
I need the PWM outputs of the motor control to go from these outputs, depending on the position of the control levers.
I'm completely lost in your code.
So far I have a functional simple communication with the control, but I need to keep your protocol in MULTI.
I will be happy for any suggestions and advice.
Thank you for this beautiful project.

George
![Controlling-MX1508-motor-driver](https://user-images.githubusercontent.com/44894972/81923134-79ae5280-95dd-11ea-8f6c-3e22490e11db.png)

**Comment by soligen2010** [comment]
Mapping to channels is something you would do in the transmitter, not in the RX code. All the RX outputs are PWM, so you need to map the sticks to the desired channels in the transmitter.  You should be able to find tutorials on-line for your transmitter than can explain this much better than I can.

My other suggestion would be just to wire the things differently on the receiver so the channels with the data you want are wired to the correct port of your PWM controller.

I do highly recommend that **you not change the Throttle channel**.  For safety, this channel has a disarm feature when the signal is lost.

**Comment by stanekTM** [comment]
Thanks Soligen for the suggestions
work in progress, this protocol will be transferred to the "OpenAVRc" project, for direct control of SPI thanks to our developer.
You could add some information to your TX "Cabell" transmitter, such as a diagram, photo, etc. The TX transmitter looks interesting and you don't always need a big processor.
Thank you George

**Comment by soligen2010** [comment]
For me, the transmitter project is obsolete.  I transferred the protocol to the MultiProtocol project and that is what I use.  Making changes for each model was just too painful in the TX project because code needed to be re-compiled for each change.  With MultiProtocol, all the model editing is done with OpenTX (or other TX software), and is what I recommend.

I have no plans to re-visit or add documentation for the TX project - I only uploaded it to Github in case someone wanted it and was willing to wade through the code to figure it out.  The code organization is not the greatest - it grew organically as I learned what I wanted to do with the protocol.  This is why I turned off the ability to open issues on the TX project.  I think the RX code is better organized.

**Comment by stanekTM** [comment]
Hi Denis,
Yes, I understand, I mainly use the OpenAVRc and OpenTX pistols.
I built my own "RF laps counter" for RC car races. I'm currently working on micro cars, so I was mainly interested in your great RX with the integration of motor drivers. For friends, I want to build a simple basic Cabell TX 2x joystick from the TX set transmitters, no display. I'll see how I manage integration on the ATmega 328P. Making pistol transmitters based on OpenTX or MULTI would drive me crazy.
Thank you for the information and protocol.
Regards George
